title: Default Page

columns:
  main:
    width: 2/3
    fields:
      text:
        label: Text
        type: textarea
  sidebar:
    width: 1/3
    fields:
      downloads:
        label: Verknüpfte Dateien
        type: files
      Toggle:
        label: Toggle
        type: toggle
        text: Sidebar anzeigen?
      url:
        label: URL
        type: url
      name:
        label: Bezeichnung des Links
        type: text