title: KGS Rastede

tabs:
  alles:
    preset: pages
    unlisted: true

  # Lesezeichen
  notfallbereich:
    label: Notfall
    icon: bookmark
    fields:
      togglenotfall:
        label: Liegt ein Notfall vor?
        help: Deaktiviert die normale Homepage
        type: toggle
        text:
          - "Notfallbetrieb (normale Homepage deaktivieren)"
          - "Regelbetrieb"
      notfalltext:
        label: text für den Notfall
        type: textarea

  # Lesezeichen
  bookmark:
    label: Lesezeichen
    icon: bookmark
    sections:
      seiten:
        type: fields
        fields:
          pages:
